## Pourquoi NumPy ?

NumPy est une bibliothèque fondamentale pour le calcul scientifique en Python.

Avantages :
- Très rapide (écrit en C)
- Support des tableaux multidimensionnels (ndarray)
- Opérations mathématiques optimisées
- Base de la majorité des bibliothèques Data Science (Pandas, Scikit-learn, etc.)

## 1. Définir un vecteur (Array 1D)

On peut créer un tableau NumPy à partir d'une liste Python.

In [1]:
import numpy as np
A=np.array([1,2,3])
print(A)
print(type(A))

[1 2 3]
<class 'numpy.ndarray'>


## 2. Définir une matrice (Array 2D)

NumPy permet de créer des matrices multidimensionnelles.

In [2]:
A = np.array([1, 2, 3])
B = np.zeros((2, 3))
C = np.ones((2, 3))

print("A:\n", A, "\n")
print("B:\n", B, "\n")
print("C:\n", C)

A:
 [1 2 3] 

B:
 [[0. 0. 0.]
 [0. 0. 0.]] 

C:
 [[1. 1. 1.]
 [1. 1. 1.]]


## 3. Remplir une matrice avec une valeur donnée

La fonction np.full() permet de remplir un tableau avec une valeur spécifique.

In [3]:
D = np.full((2, 2), 659)
print(D)

E = np.full_like(B, 4)
print(E)

[[659 659]
 [659 659]]
[[4. 4. 4.]
 [4. 4. 4.]]


## 4. Génération de tableaux aléatoires

NumPy permet de générer des valeurs aléatoires selon différentes distributions.

In [4]:
A = np.random.randn(2, 3)   # distribution normale
B = np.random.rand(2, 3)    # distribution uniforme
C = np.random.randint(0, 10, (2, 3))  # entiers aléatoires

print("Randn:\n", A, "\n")
print("Rand:\n", B, "\n")
print("RandInt:\n", C)

Randn:
 [[-2.81235638 -1.05508803  0.96503773]
 [-0.11624788  1.34151135  1.35855629]] 

Rand:
 [[0.89650708 0.61340439 0.46270916]
 [0.46492835 0.92776127 0.77206772]] 

RandInt:
 [[2 9 7]
 [8 4 9]]


## 5. Informations sur un tableau

On peut récupérer :
- shape : dimensions
- ndim : nombre de dimensions
- size : nombre total d’éléments

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", A.shape)
print("Dimensions:", A.ndim)
print("Size:", A.size)

Shape: (2, 3)
Dimensions: 2
Size: 6


# création d'un tableau de shape (2,3)

In [6]:
A=np.zeros((2,3))
A

array([[0., 0., 0.],
       [0., 0., 0.]])

# combien de valeurs

In [7]:
A.size

6

# combien de dimensions

In [ ]:
A.ndim

2

# comment appler les tableau

In [10]:
a=np.array([[1,2,3,4,5,6,7],
           [8,9,10,11,12,13,14]])

In [13]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
a[1]

array([ 8,  9, 10, 11, 12, 13, 14])